version: '2.6'

services:
  backend:
    container_name: totem_backend
    build: ./backend
    networks:
      - default
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
    ports:
      - '1337:1337'
    volumes:
      - strapi_db:/api/src/.tmp
      - uploads:/api/src/public/uploads
  frontend:
    container_name: totem_ui
    build:
      context: ./front
      args:
        API_BASE_URL: 'http://localhost:1337'
    networks:
      - default
    env_file:
      - ./front/.env
    ports:
      - '3000:3000'
    depends_on:
      - backend


networks:
  default:
    name: app-network

volumes:
  strapi_db:
  uploads: